name = "solitary-mouse-58d1"
main = "src/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[vars]
INITIAL_COUNT = "1"

[[kv_namespaces]]
binding = "VIEWS"
id = "79c6dc70370d48018ca4dc372a42e4e1"

